# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    app.mailer_from: '%env(MAILER_FROM)%'
    app.base_url:    '%env(APP_BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $mailerFrom: '%app.mailer_from%'
            string $mailFrom:   '%app.mailer_from%'
            string $appBaseUrl: '%app.base_url%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
