parameters:
    locale: 'pt_BR'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\\Email\\Contract\\EmailTransportInterface: '@App\\Email\\Transport\\ResendEmailTransport'
    App\\Email\\Contract\\EmailEventLoggerInterface: '@App\\Email\\Logging\\MonologEmailEventLogger'
